name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        dependencies: ["releases-only", "upstream-dev"]
    steps:
      - uses: actions/checkout@v3
      - name: 🔁 Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: 🎯 Check cache hit
        run: echo '${{ steps.setup-python.outputs.cache-hit }}'
      - name: 🌈 Install pangeo-forge-recipes package
        shell: bash -l {0}
        run: |
          python -m pip install -e  ".[dev]"
      # FIXME: re-implement upstream-dev with pip
      - name: 🏄‍♂️ Run Tests
        shell: bash -l {0}
        run: |
          py.test tests -v \
            --cov=pangeo_forge_recipes --cov-config .coveragerc \
            --cov-report term-missing \
            --cov-report xml \
            --durations=10 --durations-min=1.0
      - name: 🚦 Run Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
